### ISSUE TITLE
npx error

### ISSUE THREAD

**Issue by rweng** [chrisguttandin/angular-prerender#25] opened 2018-11-30 13:36 UTC
Hi there, just wanted to let you know that it works nicely for the simple testing app I got. However, it seems right now you have to add `angular-prerender` to the dependencies, `npx angular-prerender` throws an error (even with the simple universal example from the readme).

```
→ npx angular-prerender
No routes could be retrieved thus the default route at "/" will be added.
(node:33634) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subscribe' of undefined
    at new ApplicationRef (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:16824:41)
    at _createClass (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:19860:24)
    at _createProviderInstance (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:19822:30)
    at initNgModule (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:19755:36)
    at new NgModuleRef_ (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:20482:13)
    at createNgModuleRef (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:20471:16)
    at Object.debugCreateNgModuleRef [as createNgModuleRef] (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:22302:16)
    at NgModuleFactory_.create (/Users/rweng/Code/playground/universe/node_modules/@angular/core/bundles/core.umd.js:23030:29)
    at /Users/rweng/.npm/_npx/33634/lib/node_modules/angular-prerender/node_modules/@angular/core/bundles/core.umd.js:16667:47
    at ZoneDelegate.invoke (/Users/rweng/.npm/_npx/33634/lib/node_modules/angular-prerender/node_modules/zone.js/dist/zone-node.js:388:26)
(node:33634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:33634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by chrisguttandin** [comment] 2018-11-30 16:36
Hi @rweng, thanks for reporting this.

I can reproduce the issue. I have the feeling that the directories are not resolved correctly when using npx.

I don't know yet how to debug this. My plan is to add a verbose mode first which will hopefully show where the problem is.

**Comment by chrisguttandin** [comment] 2018-11-30 22:06
Hi @rweng,

after releasing some versions today, I finally found a fix. Version 3.2 works with npx again.

The problem was that angular-prerender defined many packages (like @angular/core) as direct dependencies. When running angular-prerender via npx those packages were installed twice. This caused the initial problem.

To overcome this, I defined the packages which are part of an Angular CLI project anyway as peer dependencies. However that caused another problem. npx does not load peer dependencies. This is why I wrote a (very ugly) hack which resolves the peer dependencies dynamically.

I will close this issue now. Please let me know if the issue keeps coming back.

**Closed by chrisguttandin** 2018-11-30 22:06 UTC

**Comment by rweng** [comment] 2018-12-01 06:13
Neat, thank you. Looking forward to seeing this project evolve!

**Comment by MeTheCat** [comment] 2019-12-03 02:56
I've got the exact same error trying to run npx angular-prerender on my project:
```
The route at "/**" will not be rendered because it contains a wildcard.
(node:11676) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subscribe' of undefined
```

**Comment by chrisguttandin** [comment] 2019-12-03 22:05
Hi @MeTheCat,

can you please provide the full stack trace? Otherwise it's hard to debug.

Is the application you are using available somewhere or is it a closed source codebase?

**Comment by MeTheCat** [comment] 2019-12-04 14:18
Sure, there it is:

```
H:\myApp>npx angular-prerender
No routes could be retrieved thus the default route at "/" will be added.
(node:4740) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'subscribe' of undefined
    at new core_ApplicationRef (H:\myApp\dist\server\main.js:73198:37)
    at _createClass (H:\myApp\dist\server\main.js:63871:20)
    at _createProviderInstance (H:\myApp\dist\server\main.js:63825:26)
    at initNgModule (H:\myApp\dist\server\main.js:63731:32)
    at new NgModuleRef_ (H:\myApp\dist\server\main.js:64841:9)
    at Object.createNgModuleRef (H:\myApp\dist\server\main.js:64824:12)
    at NgModuleFactory_.create (H:\myApp\dist\server\main.js:78167:25)
    at H:\myApp\node_modules\@angular\core\bundles\core.umd.js:26863:47
    at ZoneDelegate.invoke (H:\myApp\node_modules\zone.js\dist\zone-node.js:391:26)
    at Object.onInvoke (H:\myApp\node_modules\@angular\core\bundles\core.umd.js:26371:37)
(node:4740) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4740) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Angular CLI: 8.3.9
Node: 12.13.1
OS: win32 x64
Angular: 8.2.10

It should be reproducible with ng-toolkit universal:
```
ng new myApp
cd myApp
ng add @ng-toolkit/universal
npm run build:prerender
npm install angular-prerender --save-dev
npx angular-prerender
```
My project is not using ng-toolkit, but the error is the same for me.
Hope it helps!

**Comment by chrisguttandin** [comment] 2019-12-07 12:04
Thanks for providing further details. I think I was able to identify the problem. @ng-toolkit is using the `--bundleDependencies all` to render the server bundle. This is a bit unfortunate because that encapsulates all the dependencies. `angular-prerender` will then essentially create a second instance of Angular which is then causing the error.

By reading the comments on angular/universal#1206 I think we can expect the server bundle to export the necessary functions from `@angular/core` and `@angular/platform-server` in version 9. But for now I think the only thing we can do is not using `--bundleDependencies all`.

Please let me know if that solves the problem for you as well.
